from aiogram.utils.callback_data import CallbackData


exception_callback = CallbackData("full_exception", "e_id")
